// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltwsevcmuddlefroaxff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0d3NldmNtdWRkbGVmcm9heGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NzU3NDAsImV4cCI6MjA1NjU1MTc0MH0.irVHk3JXVSAGZQyy_xAhgANZiXPZjxUuqra3KR2oPf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);